"""
Healing Agent — ML-powered grid recovery system.

Replaces the rule-based RedispatchEngine with a trained model
that reads the broken grid state and decides:
  - Which technologies to ramp up (Hydro, Gas, Coal)
  - How much import to pull
  - Whether load shedding is needed

Uses HistGradientBoostingRegressor (same philosophy as HybridCorrector)
for fast, interpretable, no-GPU-needed inference.

Training data comes from chaos_scenarios.parquet generated by the
ScenarioEngine + RedispatchEngine oracle.
"""

import os
import math
import pickle
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

from .simulator import GridState, Generator, RAMP_RATES
from .redispatch import TECH_COSTS, TECH_EMISSIONS, DISPATCH_WINDOW_MIN


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in km between two geographic points."""
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2
    return R * 2 * math.asin(math.sqrt(a))



# Feature names matching ScenarioEngine._build_feature_vector()
FEATURE_NAMES = [
    "f_demand", "f_gen", "f_deficit", "f_deficit_ratio",
    "f_freq", "f_freq_dev",
    "f_offline_gens", "f_overloaded_lines", "f_reserve", "f_imports",
    "f_hydro", "f_gas", "f_coal", "f_nuclear", "f_solar", "f_wind",
]

# Action names matching ScenarioEngine._build_action_vector()
ACTION_NAMES = [
    "a_ramp_hydro", "a_ramp_gas", "a_ramp_coal", "a_ramp_nuclear",
    "a_pull_imports", "a_remaining_deficit", "a_cost",
]



class HealingAgent:
    """
    ML-powered grid healing agent.
    
    Given a broken grid state (post-fault features), predicts the optimal
    redispatch actions to restore the grid with minimum cost while
    maximizing load served.
    """

    def __init__(self):
        self.model: Optional[MultiOutputRegressor] = None
        self.is_trained = False
        self.training_metrics: dict = {}

    def train(self, data_path: str = "data/processed/chaos_scenarios.parquet") -> dict:
        """
        Train the healing agent on the generated scenario dataset.
        
        Returns training metrics.
        """
        print("[HealingAgent] Loading training data...")
        df = pd.read_parquet(data_path)
        print(f"[HealingAgent] Dataset: {len(df)} scenarios")

        # Extract features and targets
        X = df[FEATURE_NAMES].values
        y = df[ACTION_NAMES].values

        # Remove rows with NaN
        valid_mask = ~(np.isnan(X).any(axis=1) | np.isnan(y).any(axis=1))
        X = X[valid_mask]
        y = y[valid_mask]
        print(f"[HealingAgent] Valid samples: {len(X)}")

        # Train/test split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        # Train multi-output regressor
        print("[HealingAgent] Training HistGradientBoosting model...")
        base_model = HistGradientBoostingRegressor(
            max_iter=300,
            max_depth=8,
            learning_rate=0.05,
            min_samples_leaf=10,
            l2_regularization=0.1,
            random_state=42,
        )
        self.model = MultiOutputRegressor(base_model)
        self.model.fit(X_train, y_train)
        self.is_trained = True

        # Evaluate
        y_pred = self.model.predict(X_test)
        metrics = {}
        for i, name in enumerate(ACTION_NAMES):
            mae = mean_absolute_error(y_test[:, i], y_pred[:, i])
            r2 = r2_score(y_test[:, i], y_pred[:, i])
            metrics[name] = {"mae": round(mae, 2), "r2": round(r2, 4)}
            print(f"  {name}: MAE={mae:.2f}, R2={r2:.4f}")

        # Overall metrics
        metrics["overall_r2"] = round(
            r2_score(y_test, y_pred, multioutput="uniform_average"), 4
        )
        metrics["n_train"] = len(X_train)
        metrics["n_test"] = len(X_test)
        self.training_metrics = metrics

        print(f"[HealingAgent] Overall R2: {metrics['overall_r2']:.4f}")
        return metrics

    def predict(self, grid_state: GridState) -> dict:
        """
        Given a broken grid state, predict optimal healing actions.
        
        Returns a dict with recommended actions and predicted outcomes.
        Backward-compatible with both the legacy 6-output model and the
        new 7-output model (which adds nuclear ramp as a separate target).
        """
        if not self.is_trained:
            raise RuntimeError("HealingAgent not trained. Call train() first.")

        # Build feature vector from the current grid state
        features = self._extract_features(grid_state)
        X = np.array(features).reshape(1, -1)

        # Predict
        prediction = self.model.predict(X)[0]

        # Clamp to non-negative
        prediction = np.maximum(prediction, 0.0)

        n_out = len(prediction)

        if n_out >= 7:
            # New 7-output format: [hydro, gas, coal, nuclear, imports, deficit, cost]
            predicted_cost        = float(prediction[6])
            predicted_deficit     = float(prediction[5])
            tech_ramps = [
                ("Hydro",   prediction[0]),
                ("Gas",     prediction[1]),
                ("Coal",    prediction[2]),
                ("Nuclear", prediction[3]),
            ]
            import_idx = 4
        else:
            # Legacy 6-output format: [hydro, gas, coal, imports, deficit, cost]
            predicted_cost        = float(prediction[5])
            predicted_deficit     = float(prediction[4])
            tech_ramps = [
                ("Hydro", prediction[0]),
                ("Gas",   prediction[1]),
                ("Coal",  prediction[2]),
            ]
            import_idx = 3

        result = {
            "status": "AI Healing Recommendation",
            "actions": [],
            "predicted_cost_eur": round(predicted_cost, 0),
            "predicted_remaining_deficit_mw": round(predicted_deficit, 1),
        }

        # Build action list
        for tech, ramp_mw in tech_ramps:
            if ramp_mw > 1.0:  # Only include meaningful actions
                result["actions"].append({
                    "type": "ramp_up",
                    "technology": tech,
                    "recommended_mw": round(float(ramp_mw), 1),
                })

        if prediction[import_idx] > 1.0:
            result["actions"].append({
                "type": "emergency_import",
                "recommended_mw": round(float(prediction[import_idx]), 1),
            })

        return result



    def apply_healing(self, grid_state: GridState) -> dict:
        """
        Predict AND apply the healing actions to the grid state.
        Modifies state in-place.
        
        Returns the action log.
        """
        recommendation = self.predict(grid_state)
        actually_ramped = {}
        detailed_actions = []

        total_target_mw = 0.0
        import_target_mw = 0.0
        
        for action in recommendation["actions"]:
            if action["type"] == "ramp_up":
                total_target_mw += action["recommended_mw"]
            elif action["type"] == "emergency_import":
                import_target_mw += action["recommended_mw"]

        import math

        # ─── Phase 0: Buffer Discharge (cheapest, cleanest source) ───
        buffer = getattr(grid_state, 'virtual_buffer', None)
        buffer_dispatched_mw = 0.0
        if buffer is not None and buffer.total_stored_mwh() > 1.0:
            # Identify deficit regions from the current DCPF state
            deficit_regions = {
                r: -exc
                for r, exc in grid_state.regional_excess_mw.items()
                if exc < -0.1
            }
            if not deficit_regions and grid_state.deficit_mw > 0.1:
                # Fallback: spread deficit proportionally across demand regions
                total_demand = grid_state.total_demand_mw or 1.0
                for r, d in grid_state.regional_demand_mw.items():
                    deficit_regions[r] = grid_state.deficit_mw * (d / total_demand)

            if deficit_regions:
                buffer_actions = buffer.dispatch_to_cover_deficit(
                    deficit_regions, window_hours=1.0
                )
                for ba in buffer_actions:
                    buffer_dispatched_mw += ba["discharged_mw"]
                    detailed_actions.append(ba)

                # Reduce how much we need from conventional plants
                total_target_mw = max(0.0, total_target_mw - buffer_dispatched_mw)

                # L5 fix: deficit_mw is a computed property (can't assign directly).
                # Buffer discharge is a real power injection — treat it like an import,
                # which correctly reduces deficit_mw = demand - (gen + imports - losses).
                grid_state.imports_mw = grid_state.imports_mw + buffer_dispatched_mw

                # Update regional_excess_mw for regions that received buffer power
                for ba in buffer_actions:
                    to_r = ba["to_region"]
                    if to_r in grid_state.regional_excess_mw:
                        grid_state.regional_excess_mw[to_r] = (
                            grid_state.regional_excess_mw[to_r] + ba["discharged_mw"]
                        )

        if buffer_dispatched_mw > 0.1:
            actually_ramped["Buffer"] = round(buffer_dispatched_mw, 1)

        
        # Identify fault locations (offline generators)
        offline_gens = [g for g in grid_state.generators.values() if not g.is_online]
        
        # Calculate distance-weighted reserve scores for ALL generators
        weights = {}

        # Pre-compute max reserve for normalization
        max_reserve_mw = max(
            (g.available_reserve_mw for g in grid_state.generators.values()
             if g.is_online and g.technology not in ["Wind", "Solar"]),
            default=1.0
        ) or 1.0

        # Highest merit-order cost sets scale: lower cost = higher merit
        max_cost = max(TECH_COSTS.values()) or 100.0

        for gen in grid_state.generators.values():
            if not gen.is_online:
                weights[gen.id] = 0.0
                detailed_actions.append({
                    "type": "score_log",
                    "generator_id": gen.id,
                    "score": 0.0
                })
                continue

            # Weather-dependent sources cannot be manually commanded
            if gen.technology in ["Wind", "Solar"]:
                weights[gen.id] = 0.0
                detailed_actions.append({
                    "type": "score_log",
                    "generator_id": gen.id,
                    "score": 0.0
                })
                continue

            # ── 1. Reserve factor (normalised 0-1) ──
            # Prevents a large hydro plant at 600km from always outscoring
            # a smaller gas plant at 0km purely due to MWh size.
            reserve_factor = max(0.01, gen.available_reserve_mw) / max_reserve_mw

            # ── 2. Distance factor (Haversine km to nearest offline generator) ──
            if offline_gens:
                min_dist_km = min(
                    _haversine_km(gen.lat, gen.lon, og.lat, og.lon)
                    for og in offline_gens
                )
            else:
                min_dist_km = 0.0

            # Proximity weight: exponential decay over 800 km
            # At 0km: 1.0 | At 400km: 0.61 | At 800km: 0.37 | At 1600km: 0.14
            proximity_factor = math.exp(-min_dist_km / 800.0)

            # ── 3. Economic merit (cheaper tech = higher score) ──
            tech_cost = TECH_COSTS.get(gen.technology, 50.0)
            merit_factor = 1.0 - (tech_cost / (max_cost + 1.0))  # 0-1, higher=cheaper

            # ── 4. Emissions factor ──
            emissions = TECH_EMISSIONS.get(gen.technology, 0.0)
            clean_factor = 1.0 / (emissions + 0.1)  # 0.1 = near-zero emissions
            clean_factor_norm = min(1.0, clean_factor / 10.0)  # cap at 1

            # ── Combined score: weighted geometric mean ──
            # Weights: reserve=0.3, proximity=0.35, merit=0.25, emissions=0.10
            score = (
                reserve_factor   ** 0.30 *
                proximity_factor ** 0.35 *
                (merit_factor + 0.01) ** 0.25 *
                (clean_factor_norm + 0.01) ** 0.10
            ) * 100.0  # scale 0-100 for readability

            weights[gen.id] = score

            detailed_actions.append({
                "type": "score_log",
                "generator_id": gen.id,
                "score": round(score, 4),
                "reserve_mw": round(gen.available_reserve_mw, 1),
                "dist_km": round(min_dist_km, 1),
                "merit": round(merit_factor, 3),
            })


        # --- Phase 3: Spatial Allocation Algorithm ---
        # 1. Identify regional excesses and deficits
        deficit_regions = {r: -exc for r, exc in grid_state.regional_excess_mw.items() if exc < -0.1}
        excess_regions = {r: exc for r, exc in grid_state.regional_excess_mw.items() if exc > 0.1}
        
        # 2. Route power from excess regions to deficit regions (Distance & Loss Aware)
        from digital_twin.virtual_buffer import _region_distance_km, _transmission_efficiency, normalize_region
        ISLAND_REGIONS = {"Baleares", "Canarias", "Ceuta", "Melilla", "Islas Canarias", "Islas Baleares"}

        for d_r in list(deficit_regions.keys()):
            if deficit_regions[d_r] <= 0.1:
                continue
                
            norm_d_r = normalize_region(d_r)
            d_is_island = norm_d_r in ISLAND_REGIONS

            # Find candidate excess regions and sort by distance (closest first = max efficiency)
            candidates = []
            for e_r, exc in excess_regions.items():
                if exc <= 0.1:
                    continue
                
                norm_e_r = normalize_region(e_r)
                e_is_island = norm_e_r in ISLAND_REGIONS
                
                # Island isolation constraint
                if d_is_island != e_is_island:
                    continue
                if d_is_island and e_is_island and norm_d_r != norm_e_r:
                    continue
                    
                dist_km = _region_distance_km(norm_e_r, norm_d_r)
                eff = _transmission_efficiency(dist_km)
                candidates.append((dist_km, eff, e_r))
                
            candidates.sort(key=lambda x: x[0])  # Shortest distance first

            for dist_km, eff, e_r in candidates:
                if deficit_regions[d_r] <= 0.1:
                    break
                if excess_regions[e_r] <= 0.1:
                    continue
                
                needed = deficit_regions[d_r]
                available = excess_regions[e_r]
                
                if available * eff >= needed:
                    pull = needed / eff
                    arrive = needed
                else:
                    pull = available
                    arrive = available * eff
                    
                deficit_regions[d_r] -= arrive
                excess_regions[e_r] -= pull
                
                detailed_actions.append({
                    "type": "power_transfer",
                    "from_region": e_r,
                    "to_region": d_r,
                    "transferred_mw": round(arrive, 1),
                    "sent_mw": round(pull, 1),
                    "distance_km": round(dist_km, 1),
                    "efficiency": round(eff, 3)
                })
        
        # 3. Only ramp up conventional plants if there is remaining global deficit
        # We override total_target_mw with the actual remaining unfulfilled deficit
        unfulfilled_deficit = sum(deficit_regions.values())
        total_target_mw = max(total_target_mw, unfulfilled_deficit)

        if total_target_mw > 0.1:
            # Pool ALL online generators with spare capacity to cover the total target.
            # Exclusions:
            #   - Weather-dependent (Wind, Solar): can't be commanded
            #   - Nuclear: Fix #9 — operates as must-run baseload; legally and technically
            #     prohibited from fast ramping during emergencies in Spain.
            FAST_RAMP_EXCLUDED = ["Wind", "Solar", "Nuclear"]
            available = [
                g for g in grid_state.generators.values()
                if g.is_online and g.available_reserve_mw > 0
                and g.technology not in FAST_RAMP_EXCLUDED
            ]
            
            allocations = {g.id: 0.0 for g in available}
            remaining_target = total_target_mw
            active_gens = list(available)

            # Iteratively allocate total_target_mw without exceeding any generator's reserve
            while remaining_target > 0.01 and active_gens:
                total_weight = sum(weights[g.id] for g in active_gens)
                if total_weight <= 0:
                    total_weight = len(active_gens)
                    for g in active_gens:
                        weights[g.id] = 1.0

                tentative = {}
                for gen in active_gens:
                    tentative[gen.id] = (weights[gen.id] / total_weight) * remaining_target

                next_active = []
                for gen in active_gens:
                    space = gen.available_reserve_mw - allocations[gen.id]
                    if tentative[gen.id] >= space:
                        allocations[gen.id] += space
                        remaining_target -= space
                    else:
                        allocations[gen.id] += tentative[gen.id]
                        remaining_target -= tentative[gen.id]
                        next_active.append(gen)

                if len(next_active) == len(active_gens):
                    break  # No generator was capped, allocation is complete
                active_gens = next_active

            for gen in available:
                ramp = allocations[gen.id]
                if ramp > 0.1:
                    tech = gen.technology
                    
                    # Fix #6: Enforce physical ramp-rate cap.
                    # A gas plant at 20 MW/min over a 15-min dispatch window can
                    # only increase by 300 MW max. Cannot teleport power.
                    max_ramp_mw = RAMP_RATES.get(tech, 10.0) * DISPATCH_WINDOW_MIN
                    ramp = min(ramp, max_ramp_mw)
                    
                    if ramp < 0.1:
                        continue
                    
                    gen.current_output_mw += ramp
                    actually_ramped[tech] = actually_ramped.get(tech, 0.0) + ramp
                    
                    # Log the specific generator action
                    cost_per_mwh = TECH_COSTS.get(tech, 65.0)
                    detailed_actions.append({
                        "type": "ramp_up",
                        "generator_id": gen.id,
                        "technology": tech,
                        "region": gen.region,
                        "ramped_mw": round(ramp, 1),
                        "new_output_mw": round(gen.current_output_mw, 1),
                        "cost_eur": round(ramp * cost_per_mwh, 0),
                        "score": round(weights[gen.id], 4)
                    })

        if import_target_mw > 0.1:
            target_mw = import_target_mw
            # Pull imports up to interconnection limits
            total_capacity = sum(grid_state.interconnections.values())
            pullable = min(target_mw, max(0, total_capacity * 0.7 - grid_state.imports_mw))
            grid_state.imports_mw += pullable
            actually_ramped["Import"] = round(pullable, 1)
            
            detailed_actions.append({
                "type": "emergency_import",
                "imported_mw": round(pullable, 1),
                "cost_eur": round(pullable * TECH_COSTS.get("Import", 90.0), 0),
                "sources": {"Interconnections": round(pullable, 1)}
            })

        # Fix D1: Dynamic frequency recovery
        # Include buffer power in total_ramped — pumped hydro / BESS physically
        # injects power and provides real inertia contribution (L8 fix)
        total_ramped = (
            sum(a.get("ramped_mw", 0) for a in detailed_actions if a.get("type") == "ramp_up") +
            sum(a.get("imported_mw", 0) for a in detailed_actions if a.get("type") == "emergency_import") +
            buffer_dispatched_mw  # Buffer (pumped hydro/BESS) contributes real power injection
        )
        if total_ramped > 0 and grid_state.frequency_hz < 50.0:
            from .simulator import INERTIA_CONSTANTS
            H_sys_total = 0.0
            S_sys_total = 0.0
            for g in grid_state.generators.values():
                if g.is_online and g.technology in INERTIA_CONSTANTS:
                    h = INERTIA_CONSTANTS[g.technology]
                    if h > 0:
                        H_sys_total += h * g.installed_capacity_mw
                        S_sys_total += g.installed_capacity_mw
            # Add synthetic inertia from BESS if any
            bess_cap = sum(g.installed_capacity_mw for g in grid_state.generators.values() if g.is_online and g.technology == "BESS")
            if bess_cap > 0:
                H_sys_total += 3.0 * bess_cap
                S_sys_total += bess_cap
                
            H_sys = H_sys_total / max(S_sys_total, 1.0)
            if S_sys_total > 0 and H_sys > 0:
                recovery_f = (total_ramped / (2 * H_sys * S_sys_total)) * 50.0
                grid_state.frequency_hz = min(50.0, grid_state.frequency_hz + recovery_f)

        recommendation["actions"] = detailed_actions
        recommendation["actually_ramped"] = actually_ramped
        recommendation["post_healing_deficit_mw"] = round(grid_state.deficit_mw, 1)
        recommendation["post_healing_frequency_hz"] = round(grid_state.frequency_hz, 3)
        recommendation["buffer_dispatched_mw"] = round(buffer_dispatched_mw, 1)
        recommendation["buffer_summary"] = buffer.summary() if buffer else {"total_stored_mwh": 0}

        return recommendation


    def _extract_features(self, state: GridState) -> list:
        """Extract the feature vector from a GridState object."""
        summary = state.summary()
        mix = summary.get("generation_mix", {})

        total_demand = summary["total_demand_mw"]
        total_gen = summary["total_generation_mw"]
        deficit = summary["deficit_mw"]
        deficit_ratio = deficit / max(total_demand, 1.0)

        return [
            total_demand,
            total_gen,
            deficit,
            deficit_ratio,
            summary["frequency_hz"],
            abs(50.0 - summary["frequency_hz"]),
            summary["offline_generators"],
            summary["overloaded_lines"],
            summary["reserve_margin_pct"],
            summary["imports_mw"],
            mix.get("Hydro", 0),
            mix.get("Gas", 0),
            mix.get("Coal", 0),
            mix.get("Nuclear", 0),
            mix.get("Solar", 0),
            mix.get("Wind", 0),
        ]

    def save(self, path: str = "data/models/healing_agent.pkl"):
        """Save the trained model to disk."""
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            pickle.dump({
                "model": self.model,
                "metrics": self.training_metrics,
            }, f)
        print(f"[HealingAgent] Saved to {path}")

    def load(self, path: str = "data/models/healing_agent.pkl"):
        """Load a trained model from disk."""
        with open(path, "rb") as f:
            data = pickle.load(f)
        self.model = data["model"]
        self.training_metrics = data.get("metrics", {})
        self.is_trained = True
        print(f"[HealingAgent] Loaded from {path}")
